CREATE TABLE SALDO (
  ID SMALLINT PRIMARY KEY AUTO_INCREMENT,
  VALOR SMALLINT NOT NULL,
  QUANTIDADE SMALLINT NOT NULL,
  PRECO_TOTAL DECIMAL(6,2) SUM() AS SALDO STORED;
);

SELECT MAX() AS PREÇOMAX FROM (NOME DA TABLE)
SELECT MIN() AS PREÇOMIN FROM (NOME DA TABLE)
SELECT AVG() AS MEDIA FROM (NOME DA TABLE)
SELECT SUM(SALDO) AS PRECO_TOTAL  FROM entrada